// @ts-check
const { test, expect } = require('@playwright/test');
const { error } = require('console');
const path = require('path');

const API_BASE_URL = 'https://api.openweathermap.org/data/2.5';
const API_KEY = '6f1e4fbbbdc9773df141bce119a0c2fd';
const BASE_URL = 'http://localhost:8080';
const CITIES = ['London', 'Wrocław', 'Dubai', 'Vancouver', 'paris', 'los angeles', 'cairo', 'kathmandu', 'la paz'];


async function accessingBets(page) {
  // Simulate entering a city and pressing Enter (this triggers the fetchWeather function)
  await page.locator('#city').fill('London');
  await page.locator('#city').press('Enter');

  // Wait for the odds to be displayed (simulate odds based on the API response)
  await page.waitForSelector('#betRain');
  await expect(page.locator('#betRain')).toBeVisible();
  await expect(page.locator('#betClouds')).toBeVisible();
  await expect(page.locator('#betFog')).toBeVisible();
  await page.waitForSelector('#oddsRain:has-text(":")');
}

async function extraxtingOdds(page) {
  // Extract the odds generated by the app
  // Market: Rain
  let rainText = await page.locator('#oddsRain').textContent();
  let rainOdds = parseFloat(rainText.split(': ')[1]);
  console.log('➡️ ODDS - RAIN:', rainOdds);
  let noRainText = await page.locator('#oddsNoRain').textContent();
  let noRainOdds = parseFloat(noRainText.split(': ')[1]);
  console.log('➡️ ODDS - NO RAIN:', noRainOdds);

  // Market: Clouds
  let cloudsText = await page.locator('#oddsClouds').textContent();
  let cloudsOdds = parseFloat(cloudsText.split(': ')[1]);
  console.log('➡️ ODDS - CLOUDS:', cloudsOdds);
  let noCloudsText = await page.locator('#oddsNoClouds').textContent();
  let noCloudsOdds = parseFloat(noCloudsText.split(': ')[1]);
  console.log('➡️ ODDS - NO CLOUDS:', noCloudsOdds);

  // Market: Fog
  let fogText = await page.locator('#oddsFog').textContent();
  let fogOdds = parseFloat(fogText.split(': ')[1]);
  console.log('➡️ ODDS - FOG:', fogOdds);
  let noFogText = await page.locator('#oddsNoFog').textContent();
  let noFogOdds = parseFloat(noFogText.split(': ')[1]);
  console.log('➡️ ODDS - NO FOG:', noFogOdds);

  return [rainOdds, noRainOdds, cloudsOdds, noCloudsOdds, fogOdds, noFogOdds];
}


// test.beforeEach(async ({ page }) => {
//   await page.goto(`${BASE_URL}/index.html`);
// });


test.describe('', () => {
  test('SCENARIO: Application fetches the data from API and calculates odds correctly', async ({ page }) => {
    await page.goto(`${BASE_URL}/index.html`);

    // For each city, if the weather description contains the word 'rain' (case insensitive), odds should be lower for betting on rain
    for (let i = 0; i < CITIES.length; i++) {
      // Fetching API response
      const response = await fetch(`${API_BASE_URL}/weather?q=${CITIES[i]}&appid=${API_KEY}`);
      const data = await response.json();
      const weatherDescription = data.weather[0].description;
      console.log('➡️ WEATHER DESCRIPTION:', weatherDescription);

      // Extracting the odds from the app
      await page.locator('#city').fill(CITIES[i]);
      await page.locator('#city').press('Enter');
      await page.waitForSelector('#oddsRain:has-text(":")');
      await page.waitForSelector('#oddsNoRain:has-text(":")');

      let [rainOdds, noRainOdds, cloudsOdds, noCloudsOdds, fogOdds, noFogOdds] = await extraxtingOdds(page);

      // Checking the odds for rain
      if (/rain/i.test(weatherDescription)) {
        expect(rainOdds).toBeLessThan(noRainOdds);
        expect(rainOdds).toBeLessThanOrEqual(1.8);
        expect(rainOdds).toBeGreaterThanOrEqual(1.2);
        expect(noRainOdds).toBeGreaterThanOrEqual(2.0);
        expect(noRainOdds).toBeLessThanOrEqual(3.0);
      }
      else {
        expect(noRainOdds).toBeLessThan(rainOdds);
        expect(noRainOdds).toBeLessThanOrEqual(1.8);
        expect(noRainOdds).toBeGreaterThanOrEqual(1.2);
        expect(rainOdds).toBeGreaterThanOrEqual(2.0);
        expect(rainOdds).toBeLessThanOrEqual(3.0);
      }

      // Checking the odds for clouds
      if (/cloud/i.test(weatherDescription)) {
        expect(cloudsOdds).toBeLessThan(noCloudsOdds);
        expect(cloudsOdds).toBeLessThanOrEqual(2.0);
        expect(cloudsOdds).toBeGreaterThanOrEqual(1.5);
        expect(noCloudsOdds).toBeGreaterThanOrEqual(2.0);
        expect(noCloudsOdds).toBeLessThanOrEqual(2.5);
      }
      else {
        expect(noCloudsOdds).toBeLessThan(cloudsOdds);
        expect(noCloudsOdds).toBeLessThanOrEqual(2.0);
        expect(noCloudsOdds).toBeGreaterThanOrEqual(1.5);
        expect(cloudsOdds).toBeGreaterThanOrEqual(2.0);
        expect(cloudsOdds).toBeLessThanOrEqual(2.5);
      }

      // Checking the odds for fog
      if (/fog/i.test(weatherDescription)) {
        expect(fogOdds).toBeLessThan(noFogOdds);
        expect(fogOdds).toBeLessThanOrEqual(1.3);
        expect(fogOdds).toBeGreaterThanOrEqual(1.1);
        expect(noFogOdds).toBeGreaterThanOrEqual(3.0);
        expect(noFogOdds).toBeLessThanOrEqual(4.5);
      }
      else {
        expect(noFogOdds).toBeLessThan(fogOdds);
        expect(noFogOdds).toBeLessThanOrEqual(1.3);
        expect(noFogOdds).toBeGreaterThanOrEqual(1.1);
        expect(fogOdds).toBeGreaterThanOrEqual(3.0);
        expect(fogOdds).toBeLessThanOrEqual(4.5);
      }

      // Refreshing the page
      await page.reload();
    }
  });


  test('SCENARIO: Winning bets for Rain market are calculated correctly', async ({ browser }) => {
    // Testing with browser fixture instead of page fixture
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto(`${BASE_URL}/index.html`);

    // Wait for the odds to be displayed (simulate odds based on the API response)
    await accessingBets(page);

    // Extract odds values
    let [rainOdds, noRainOdds, cloudsOdds, noCloudsOdds, fogOdds, noFogOdds] = await extraxtingOdds(page);
    console.log("☑️ Odds for Rain:", rainOdds, noRainOdds);

    // Wait for the prompt to show up, bet $11 amount
    page.on('dialog', async dialog => {
      console.log('☑️ Handling popup')
      if (dialog.type() === 'prompt') {
        expect(dialog.type()).toContain('prompt');
        expect(dialog.message()).toContain('Enter the amount you want to bet');;
        await dialog.accept('11');
      } else {
        throw error('🛑 Sth went wrong.')
      }
    })
    page.on('dialog', dialog => console.log('#️⃣ DIALOG:', dialog.message()));

    // Click on bet 
    let odds;
    if (rainOdds < noRainOdds) {
      await page.locator('#betRain').click(); // Trigger a bet on rain
      odds = rainOdds;
    } else {
      await page.locator('#betNoRain').click(); // Trigger a bet on no rain
      odds = noRainOdds;
    }

    // Check the wallet value
    let wallet = (11 * odds + (100 - 11)).toFixed(2);
    console.log('☑️ Wallet:', wallet)
    await expect(page.locator('#walletAmount')).toContainText(wallet);
  });


  test('SCENARIO: Winning bets for Clouds market are calculated correctly', async ({ browser }) => {
    // Testing with browser fixture instead of page fixture
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto(`${BASE_URL}/index.html`);

    // Wait for the odds to be displayed (simulate odds based on the API response)
    await accessingBets(page);

    // Extract odds values
    let [rainOdds, noRainOdds, cloudsOdds, noCloudsOdds, fogOdds, noFogOdds] = await extraxtingOdds(page);
    console.log("☑️ Odds for Clouds:", cloudsOdds, noCloudsOdds);

    // Wait for the prompt to show up, bet $11 amount
    page.on('dialog', async dialog => {
      console.log('☑️ Handling popup')
      if (dialog.type() === 'prompt') {
        expect(dialog.type()).toContain('prompt');
        expect(dialog.message()).toContain('Enter the amount you want to bet');;
        await dialog.accept('11');
      } else {
        throw error('🛑 Sth went wrong.')
      }
    })
    page.on('dialog', dialog => console.log('#️⃣ DIALOG:', dialog.message()));

    // Click on bet 
    let odds;
    if (cloudsOdds < noCloudsOdds) {
      await page.locator('#betClouds').click(); // Trigger a bet on clouds
      odds = cloudsOdds;
    } else {
      await page.locator('#betNoClouds').click(); // Trigger a bet on no clouds
      odds = noCloudsOdds;
    }

    // Check the wallet value
    let wallet = (11 * odds + (100 - 11)).toFixed(2);
    console.log('☑️ Wallet:', wallet)
    await expect(page.locator('#walletAmount')).toContainText(wallet);
  });


  test('SCENARIO: Winning bets for Fog market are calculated correctly', async ({ browser }) => {
    // Testing with browser fixture instead of page fixture
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto(`${BASE_URL}/index.html`);

    // Wait for the odds to be displayed (simulate odds based on the API response)
    await accessingBets(page);

    // Extract odds values
    let [rainOdds, noRainOdds, cloudsOdds, noCloudsOdds, fogOdds, noFogOdds] = await extraxtingOdds(page);
    console.log("☑️ Odds for Fog:", fogOdds, noFogOdds);

    // Wait for the prompt to show up, bet $11 amount
    page.on('dialog', async dialog => {
      console.log('☑️ Handling popup')
      if (dialog.type() === 'prompt') {
        expect(dialog.type()).toContain('prompt');
        expect(dialog.message()).toContain('Enter the amount you want to bet');;
        await dialog.accept('11');
      } else {
        throw error('🛑 Sth went wrong.')
      }
    })
    page.on('dialog', dialog => console.log('#️⃣ DIALOG:', dialog.message()));

    // Click on bet 
    let odds;
    if (fogOdds < noFogOdds) {
      await page.locator('#betFog').click(); // Trigger a bet on fog
      odds = fogOdds;
    } else {
      await page.locator('#betNoFog').click(); // Trigger a bet on no fog
      odds = noFogOdds;
    }

    // Check the wallet value
    let wallet = (11 * odds + (100 - 11)).toFixed(2);
    console.log('☑️ Wallet:', wallet)
    await expect(page.locator('#walletAmount')).toContainText(wallet);
  });


  test('SCENARIO: Loosing bets are calculated correctly', async ({ page }) => {
    await page.goto(`${BASE_URL}/index.html`);

    // Wait for the odds to be displayed (simulate odds based on the API response)
    await accessingBets(page);

    // Extract odds values
    let [rainOdds, noRainOdds, cloudsOdds, noCloudsOdds, fogOdds, noFogOdds] = await extraxtingOdds(page);

    // Wait for the prompt to show up, bet $10 amount
    page.on('dialog', async dialog => {
      console.log('☑️ Handling popup')
      if (dialog.type() === 'prompt') {
        expect(dialog.type()).toContain('prompt');
        expect(dialog.message()).toContain('Enter the amount you want to bet');;
        await dialog.accept('10');
      } else {
        throw error('🛑 Sth went wrong.')
      }
    })
    page.on('dialog', dialog => console.log('☑️☑️ DIALOG:', dialog.message()));

    // Click on bet 
    let odds;
    if (rainOdds > noRainOdds) {
      await page.locator('#betRain').click(); // Trigger a bet on rain
      odds = rainOdds;
    } else {
      await page.locator('#betNoRain').click(); // Trigger a bet on no rain
      odds = noRainOdds;
    }
    console.log('☑️ Odds:', odds)

    // Check the wallet value
    let wallet = String(100 - 10);
    console.log('☑️ Wallet:', wallet)
    await expect(page.locator('#walletAmount')).toContainText(wallet);
  })


  test('SCENARIO: Cash out offered for bets over $50 with odds greater than 1.50', async ({ page }) => {
    await page.goto(`${BASE_URL}/index.html`);

    let success = false;
    while (!success) {

      // Wait for the odds to be displayed (simulate odds based on the API response)
      await accessingBets(page);

      // Extract odds values
      let oddsValues = [];
      let [rainOdds, noRainOdds, cloudsOdds, noCloudsOdds, fogOdds, noFogOdds] = await extraxtingOdds(page);
      oddsValues.push(rainOdds, noRainOdds);

      let minValue = Math.min(...oddsValues)
      if (minValue > 1.5) {
        success = true;
        let index = oddsValues.indexOf(minValue);


        // Wait for the prompt to show up, bet over $50 amount, accept the cash out
        page.on('dialog', async dialog => {
          console.log('☑️ Handling popup')
          if (dialog.type() === 'prompt') {
            expect(dialog.type()).toContain('prompt');
            expect(dialog.message()).toContain('Enter the amount you want to bet');;
            await dialog.accept('60');
          } else {
            expect(dialog.type()).toBe('confirm');
            expect(dialog.message()).toContain('Cash out option');;
            await dialog.accept();
          }
        })
        page.on('dialog', dialog => console.log('☑️☑️ DIALOG:', dialog.message()));

        // Click on a bet 
        if (index === 0) {
          await page.locator('#betRain').click(); // Trigger a bet on rain
        } else {
          await page.locator('#betNoRain').click(); // Trigger a bet on no rain
        }


        await expect(page.locator('#walletAmount')).toHaveText('124');  // bet amount * cash out margin (60*40% = 24)

        break

      } else {
        page.reload();
      }
    }
  });


  test('SCENARIO: Freezing the market', async ({ page }) => {
    await page.goto(`${BASE_URL}/index.html`);

    let success = false;
    while (!success) {

      // Wait for the odds to be displayed (simulate odds based on the API response)
      await accessingBets(page);

      // Extract odds values
      let oddsValues = [];
      let [rainOdds, noRainOdds, cloudsOdds, noCloudsOdds, fogOdds, noFogOdds] = await extraxtingOdds(page);
      oddsValues.push(rainOdds, noRainOdds);

      let minValue = Math.min(...oddsValues)
      if (minValue > 1.5) {
        success = true;
        let index = oddsValues.indexOf(minValue);


        // Wait for the prompt to show up, bet over $50 amount, accept the cash out
        page.on('dialog', async dialog => {
          console.log('☑️ Handling popup')
          if (dialog.type() === 'prompt') {
            expect(dialog.type()).toContain('prompt');
            expect(dialog.message()).toContain('Enter the amount you want to bet');;
            await dialog.accept('95');
          } else {
            expect(dialog.type()).toBe('confirm');
            expect(dialog.message()).toContain('The betting market is suspended');;
            await dialog.accept();
          }
        })
        page.on('dialog', dialog => console.log('☑️☑️ DIALOG:', dialog.message()));

        // Click on a bet 
        if (index === 0) {
          await page.locator('#betRain').click(); // Trigger a bet on rain
        } else {
          await page.locator('#betNoRain').click(); // Trigger a bet on no rain
        }


        await expect(page.locator('#walletAmount')).toHaveText('100');

        break

      } else {
        page.reload();
      }
    }
  });
});
